### ISSUE TITLE
`getCalendarItemTypesIncludeDeleted` does not exist on `calendarItemTypeApi`

### ISSUE THREAD

**Issue by antoinepairet** [antoinepairet/icc-api#13]
`getCalendarItemTypesIncludeDeleted` does not exist on `calendarItemTypeApi`

````js
  async loadCalendarItemTypesIncludeDeleted() {
     await this.api.calendarItemTypeApi.getCalendarItemTypesIncludeDeleted().then(calendarItemTypes => {
      this.calendarItemTypesIncludeDeleted = calendarItemTypes;
    });
  }
````

See [medispring](https://github.com/antoinepairet/medispring/blob/5a5dbb5933ec8a1039590cc4fd9acb92e444ac58/apps/web-doctors/src/app/private/calendar/ms-calendar.component.ts#L257-L261)

**Comment by htr-nsi** [comment]
This method was comitted in PR [#452](https://github.com/antoinepairet/medispring/pull/452).
The icc-api submodule reference on nsi/development is : [014178672bd1cabdbd53d88707de3baf75a6cff7](https://github.com/antoinepairet/icc-api/commit/014178672bd1cabdbd53d88707de3baf75a6cff7) (last commit on icc-api master branch)

**Comment by htr-nsi** [comment]
New PR ( [#475](https://github.com/antoinepairet/medispring/pull/475)) was made with the same submodule reference ([014178672bd1cabdbd53d88707de3baf75a6cff7](https://github.com/antoinepairet/icc-api/commit/014178672bd1cabdbd53d88707de3baf75a6cff7)) in medispring repo.
